\documentclass[a4paper]{book}
\usepackage{amssymb}
\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage{fancyhdr}
\usepackage{bm}
\usepackage{pstricks}
\usepackage{qrcode}
\usepackage{subfigure}
\usepackage{graphicx}
\usepackage{lastpage}
\usepackage{booktabs,tabularx,dcolumn}
\usepackage{caption}
\usepackage{xcolor, colortbl}
\usepackage{changepage}
\usepackage{fontspec}
\usepackage{array}
\usepackage{lastpage}
\usepackage{color}  
\usepackage{hyperref}
\usepackage{cleveref}
\hypersetup{
    colorlinks=true, %set true if you want colored links
    linktoc=all,     %set to all if you want both sections and subsections linked
    linkcolor=black,  %choose some color if you want links to stand out
}
\usepackage{rotating}
\usepackage{float}
\usepackage{morefloats}
\usepackage[section]{placeins}

\newcommand{\definesamplelabel}{MPLP Inc.}
\newcommand{\definesamplename}{Information Technology}
\newcommand{\definesampleauthor}{MPA}

\pagestyle{fancy}
\fancyhf{}
\rhead{\definesamplelabel{}}
\lhead{\definesamplename{}}
\rfoot{Page \thepage}
\cfoot{v. Foundation}
\lfoot{Analyst: \definesampleauthor}

\extrafloats{300}
\maxdeadcycles=300

\begin{document}

<<Create_PDF,include=FALSE, results='hide'>>=

library(knitr)
opts_chunk$set(concordance=TRUE)
@

<<setup, include=FALSE, cache=FALSE>>=
muffleError <- function(x,options) {}
knit_hooks$set(error=muffleError)
@

<<Libraries_install,warning=FALSE,echo=FALSE, results='hide',include=FALSE>>=
install.packages("devtools")
remotes::install_github("joshuaulrich/quantmod@358-getsymbols-new.session")
install.packages("xts")
install.packages("rvest")
install.packages("tidyverse")
install.packages("stringr")
install.packages("forcats")
install.packages("lubridate")
install.packages("plotly")
install.packages("dplyr")
install.packages("PerformanceAnalytics")
install.packages("FinancialInstrument")
install.packages("foreach")
install.packages("corrplot")
install.packages("webshot")
install.packages("data.table")
@


<<Libraries,warning=FALSE,echo=FALSE, results='hide',include=FALSE>>=
library('knitr')
library('xtable')
library('quantmod')
library('xts')
library('rvest')
library('tidyverse')
library('stringr')
library('forcats')
library('lubridate')
library('plotly')
library('dplyr')
library('PerformanceAnalytics')
library('FinancialInstrument')
library('foreach')
library('corrplot')
library('webshot')
library('data.table')
library('tidyverse')

@




\title{\definesamplelabel{}\\ \definesamplename{}}

\author{MPA}

\maketitle

\thispagestyle{empty}


\begingroup
\tableofcontents
\let\clearpage\relax
\endgroup

\clearpage

\thispagestyle{empty}

\begingroup
\listoffigures
\let\clearpage\relax
\listoftables
\endgroup


\clearpage

\thispagestyle{empty}




\chapter*{Information Technology}


\setcounter{chapter}{1}


<<Get Symbols InformationTechnology1, echo=FALSE, results='hide',include=FALSE>>=

listaInformationTechnology1 <- c("AAPL","ACN","ADBE","ADI","ADP","ADSK",
"AKAM","AMAT","AMD","ANET","ANSS","APH","AVGO","BR","CDAY","CDNS","CDW",
"CRM","CSCO","CTSH","CTXS","DXC","ENPH","EPAM","FFIV","FIS","FISV","FLT",
"FTNT","GLW","GPN","HPE","HPQ","IBM","INTC","INTU","IPGP")

getSymbols(listaInformationTechnology1,auto.assign = TRUE, from="2015-11-01",to=Sys.Date()+1)

listaInformationTechnology2 <-  c("IT","JKHY","JNPR",
"KEYS","KLAC","LRCX","MA","MCHP","MPWR","MSFT","MSI","MU","NLOK","NOW","NTAP","NVDA","NXPI",
"ORCL","PAYC","PAYX","PTC","PYPL","QCOM","QRVO","SEDG","SNPS","STX","SWKS",
"TEL","TER","TRMB","TXN","TYL","V","VRSN","WDC","ZBRA")


getSymbols(listaInformationTechnology2,auto.assign = TRUE, from="2015-11-01",to=Sys.Date()+1)

@

\section{Information Technology TTR Plots}


<<Tutankamon_InformationTechnology1 ,fig.keep='all', warning=FALSE,message=FALSE ,echo=FALSE,fig=TRUE, fig.align='center', results='hide', out.width="1.1\\linewidth", fig.cap=listaInformationTechnology1>>=

fun_gen_plts = function(x){
 
  chartSeries(get(x),
              name = x,
              TA=' addBBands();
                   addBBands(draw="p");
                   addVo();
                   addMACD();
                   addADX();
                   addATR();
                   addEnvelope();
                   addCCI();
                   addCMO();
                   addDPO();
                   addRSI();
                   addSMI();
                   addWPR();
                   addCMF();
                   addKST();
                   addAroon();
                   addTDI();
                   addMFI();
                   addSAR(accel = c(0.2, 0.2),col=1);
                   addSMA(n = 20, on = 1, with.col = Cl, overlay = TRUE, col = "green");
                   addSMA(n = 50, on = 1, with.col = Cl, overlay = TRUE, col = "blue");
                   addSMA(n = 200, on = 1, with.col = Cl, overlay = TRUE, col = "red");
                   ',subset='last 3 months', theme = "white"
              )
 

}

i=1


for(i in i:length(listaInformationTechnology1)){
 
fun_gen_plts(listaInformationTechnology1[i])
 
i=i+1
 
}

@


<<Tutankamon_InformationTechnology2 ,fig.keep='all', warning=FALSE,message=FALSE ,echo=FALSE,fig=TRUE, fig.align='center', results='hide', out.width="1.1\\linewidth", fig.cap=listaInformationTechnology2>>=

fun_gen_plts = function(x){
 
  chartSeries(get(x),
              name = x,
              TA=' addBBands();
                   addBBands(draw="p");
                   addVo();
                   addMACD();
                   addADX();
                   addATR();
                   addEnvelope();
                   addCCI();
                   addCMO();
                   addDPO();
                   addRSI();
                   addSMI();
                   addWPR();
                   addCMF();
                   addKST();
                   addAroon();
                   addTDI();
                   addMFI();
                   addSAR(accel = c(0.2, 0.2),col=1);
                   addSMA(n = 20, on = 1, with.col = Cl, overlay = TRUE, col = "green");
                   addSMA(n = 50, on = 1, with.col = Cl, overlay = TRUE, col = "blue");
                   addSMA(n = 200, on = 1, with.col = Cl, overlay = TRUE, col = "red");
                   ',subset='last 3 months', theme = "white"
              )
 

}

i=1


for(i in i:length(listaInformationTechnology2)){
 
fun_gen_plts(listaInformationTechnology2[i])
 
i=i+1
 
}

@

<<parameters InformationTechnology1, echo=FALSE, results='hide',include=FALSE>>=


fun_gen_sim_InformationTechnology1 = function(x){
 
  i=1
 
  testInformationTechnology1 <- as.xts()
 
  finalInformationTechnology1 <- as.xts()
 
  for (i in i:length(listaInformationTechnology1)) {
   
    testInformationTechnology1[[i]] <- getSymbols(listaSPInformationTechnology1[i],auto.assign = FALSE, from="2015-11-01",to=Sys.Date()+1,return.class="xts")
   
  finalInformationTechnology1 <- append(finalInformationTechnology1[[i]],testInformationTechnology1[[i]])
   
  }
 
  return(finalInformationTechnology1)
 
}


fun_gen_tab_InformationTechnology1 = function(y){
 
 y <- list()
 Openy <- list()
 Closey <- list()
 Diffy <- list()
 CltoCly <- list()
 ClosePrevy <- list()
 Weeky <- list()
 Monthy <- list()
 Yeary <- list()
 Fivey <- list()

for(i in 1:length(listaInformationTechnology1)){
 
y[[i]] <- getSymbols(listaInformationTechnology1[i],auto.assign = FALSE,from="2015-11-01",to=Sys.Date()+1 ,return.class="xts")


y[[i]] <- na.locf(y[[i]], xout=seq(head(index(y[[i]]),1),tail(index(y[[i]]),1),by="1 day"))
Openy[[i]] <- as.numeric(y[[i]][end(y[[i]]),1])
Closey[[i]] <- as.numeric(y[[i]][end(y[[i]]),4])
Diffy[[i]] <- (Closey[[i]]-Openy[[i]])*100/Openy[[i]]

ClosePrevy[[i]] <- as.numeric(y[[i]][end(y[[i]])-1,4])

CltoCly[[i]] <- (Closey[[i]]-ClosePrevy[[i]])*100/ClosePrevy[[i]]

Weeky[[i]] <- (as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]][end(y[[i]])-7,1])) *100 / as.numeric(y[[i]][end(y[[i]])-7,1])


Monthy[[i]] <- (as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]][end(y[[i]])-30,4])) *100 / as.numeric(y[[i]][end(y[[i]])-30,4])



Yeary[[i]] <-(as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]]["2021-01-01",4])) *100 / as.numeric(y[[i]]["2021-01-01",4])

if(length(Yeary[[i]])==0){Yeary[[i]]= NA} else {format(round(Yeary[[i]],digits = 2),nsmall=2)}


Fivey[[i]] <- (as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]][end(y[[i]])-1825,4])) *100 / as.numeric(y[[i]][end(y[[i]])-1825,4])

if(length(Fivey[[i]])==0){Fivey[[i]]= NA} else {format(round(Fivey[[i]],digits = 2),nsmall=2)}



}
 
ResTab <- data.frame()
 
ResTab <- rbind(Diffy,CltoCly,Weeky,Monthy,Yeary,Fivey)
 

colnames(ResTab) <- listaInformationTechnology1


ResTab_transpose <- as.data.frame(t(as.matrix(ResTab)))

format.data.frame(ResTab_transpose, digits =2)

 
return(as.data.frame(ResTab_transpose))
 
}



fun_gen_sim_InformationTechnology1 = function(x){
 
  i=1
 
  testInformationTechnology1 <- as.xts()
 
  finalInformationTechnology1 <- as.xts()
 
  for (i in i:length(listaInformationTechnology1)) {
   
    testInformationTechnology1[[i]] <- getSymbols(listaInformationTechnology1[i],auto.assign = FALSE, from="2015-11-01",to=Sys.Date()+1,return.class="xts")
   
  finalInformationTechnology1 <- append(finalInformationTechnology1[[i]],testInformationTechnology1[[i]])
   
  }
 
  return(finalInformationTechnology1)
 
}

@


<<parameters InformationTechnology2, echo=FALSE, results='hide',include=FALSE>>=


fun_gen_sim_InformationTechnology2 = function(x){
 
  i=1
 
  testInformationTechnology2 <- as.xts()
 
  finalInformationTechnology2 <- as.xts()
 
  for (i in i:length(listaInformationTechnology2)) {
   
    testInformationTechnology2[[i]] <- getSymbols(listaSPInformationTechnology2[i],auto.assign = FALSE, from="2015-11-01",to=Sys.Date()+1,return.class="xts")
   
  finalInformationTechnology2 <- append(finalInformationTechnology2[[i]],testInformationTechnology2[[i]])
   
  }
 
  return(finalInformationTechnology2)
 
}


fun_gen_tab_InformationTechnology2 = function(y){
 
 y <- list()
 Openy <- list()
 Closey <- list()
 Diffy <- list()
 CltoCly <- list()
 ClosePrevy <- list()
 Weeky <- list()
 Monthy <- list()
 Yeary <- list()
 Fivey <- list()

for(i in 1:length(listaInformationTechnology2)){
 
y[[i]] <- getSymbols(listaInformationTechnology2[i],auto.assign = FALSE,from="2015-11-01",to=Sys.Date()+1 ,return.class="xts")


y[[i]] <- na.locf(y[[i]], xout=seq(head(index(y[[i]]),1),tail(index(y[[i]]),1),by="1 day"))
Openy[[i]] <- as.numeric(y[[i]][end(y[[i]]),1])
Closey[[i]] <- as.numeric(y[[i]][end(y[[i]]),4])
Diffy[[i]] <- (Closey[[i]]-Openy[[i]])*100/Openy[[i]]

ClosePrevy[[i]] <- as.numeric(y[[i]][end(y[[i]])-1,4])

CltoCly[[i]] <- (Closey[[i]]-ClosePrevy[[i]])*100/ClosePrevy[[i]]

Weeky[[i]] <- (as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]][end(y[[i]])-7,1])) *100 / as.numeric(y[[i]][end(y[[i]])-7,1])


Monthy[[i]] <- (as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]][end(y[[i]])-30,4])) *100 / as.numeric(y[[i]][end(y[[i]])-30,4])



Yeary[[i]] <-(as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]]["2021-01-01",4])) *100 / as.numeric(y[[i]]["2021-01-01",4])

if(length(Yeary[[i]])==0){Yeary[[i]]= NA} else {format(round(Yeary[[i]],digits = 2),nsmall=2)}


Fivey[[i]] <- (as.numeric(y[[i]][end(y[[i]]),4])-as.numeric(y[[i]][end(y[[i]])-1825,4])) *100 / as.numeric(y[[i]][end(y[[i]])-1825,4])

if(length(Fivey[[i]])==0){Fivey[[i]]= NA} else {format(round(Fivey[[i]],digits = 2),nsmall=2)}



}
 
ResTab <- data.frame()
 
ResTab <- rbind(Diffy,CltoCly,Weeky,Monthy,Yeary,Fivey)
 

colnames(ResTab) <- listaInformationTechnology2


ResTab_transpose <- as.data.frame(t(as.matrix(ResTab)))

format.data.frame(ResTab_transpose, digits =2)

 
return(as.data.frame(ResTab_transpose))
 
}



fun_gen_sim_InformationTechnology2 = function(x){
 
  i=1
 
  testInformationTechnology2 <- as.xts()
 
  finalInformationTechnology2 <- as.xts()
 
  for (i in i:length(listaInformationTechnology2)) {
   
    testInformationTechnology2[[i]] <- getSymbols(listaInformationTechnology2[i],auto.assign = FALSE, from="2015-11-01",to=Sys.Date()+1,return.class="xts")
   
  finalInformationTechnology2 <- append(finalInformationTechnology2[[i]],testInformationTechnology2[[i]])
   
  }
 
  return(finalInformationTechnology2)
 
}

@



\subsection{Variation for Information Technology}

<<Table_Variance_y_InformationTechnology1 , echo=FALSE, results = "asis" >>=

table.InformationTechnology1 <- fun_gen_tab_InformationTechnology1(listaInformationTechnology1)
 
 

colnames(table.InformationTechnology1) <- c("Day","CloseToClose", "Week","Month","Year","5 Years")
rownames(table.InformationTechnology1) <- listaInformationTechnology1

tex.tableInformationTechnology1 <- xtable(table.InformationTechnology1)
caption(tex.tableInformationTechnology1) <- sprintf("Variance for InformationTechnology1")
print(tex.tableInformationTechnology1,
      sep='\n' )

@


<<parameters z1 InformationTechnology1, echo=FALSE, results='hide',include=FALSE>>=


fun_gen_fun_InformationTechnology1 = function(){


FundAnalysis_z  <- c()
MarketCap    <- c()
EarningsShare <- c()
PERatio      <- c()
BookValue    <- c()
DividendYield <- c()
DividendPayDate <- c()
EarningsTimeStamp <- c()
PriceEPSEstimate <- c()
EarningsStartTime <- c()
EPSForwaerd        <- c()
EarningsEndTime  <- c()
PriceBook        <- c()
ExDividendDate   <- c()
ChangeMA50       <- c()
ChangeMA200       <- c()


i=1

for (i in i:length(listaInformationTechnology1)){
 
FundAnalysis_z[[i]] <- getQuote(listaInformationTechnology1[i], what = yahooQF(c("Market Capitalization","Earnings/Share","P/E Ratio","Book Value","Dividend Yield","Dividend Pay Date","Earnings Timestamp","Price/EPS Estimate Next Year", "Earnings Start Time","EPS Forward","Earnings End Time","Price/Book","Ex-Dividend Date","Change From 50-day Moving Average","Change From 200-day Moving Average")))

MarketCap[[i]] <- FundAnalysis_z[[i]]$`Market Capitalization`
EarningsShare[[i]] <- FundAnalysis_z[[i]]$`Earnings/Share`
PERatio[[i]]       <- FundAnalysis_z[[i]]$`P/E Ratio`
BookValue[[i]]     <- FundAnalysis_z[[i]]$`Book Value`
DividendYield[[i]] <- FundAnalysis_z[[i]]$`Dividend Yield`
DividendPayDate[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Dividend Pay Date`, origin = "1970-01-01")
EarningsTimeStamp[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Earnings Timestamp`, origin = "1970-01-01")
PriceEPSEstimate[[i]] <- FundAnalysis_z[[i]]$`Price/EPS Estimate Next Year`
EarningsStartTime[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Earnings Start Time`, origin = "1970-01-01")
EPSForwaerd[[i]] <- FundAnalysis_z[[i]]$`EPS Forward`
EarningsEndTime[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Earnings End Time`,origin = "1970-01-01")
PriceBook[[i]] <- FundAnalysis_z[[i]]$`Price/Book`
ExDividendDate[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Ex-Dividend Date`, origin = "1970-01-01")
ChangeMA50[[i]] <- FundAnalysis_z[[i]]$`Change From 50-day MA`
ChangeMA200[[i]] <- FundAnalysis_z[[i]]$`Change From 200-day MA`}

ResFunAn <- data.frame()

ResFunAn <- rbind(MarketCap,
                  EarningsShare,
                  PERatio,
                  BookValue,
                  DividendYield,
                  DividendPayDate,
                  EarningsTimeStamp,
                  PriceEPSEstimate,
                  EarningsStartTime,
                  EPSForwaerd,
                  EarningsEndTime,
                  PriceBook,
                  ExDividendDate,
                  ChangeMA50,
                  ChangeMA200)

return(ResFunAn)

}

<<Table_Variance_y_InformationTechnology2 , echo=FALSE, results = "asis" >>=

table.InformationTechnology2 <- fun_gen_tab_InformationTechnology2(listaInformationTechnology2)
 
 

colnames(table.InformationTechnology2) <- c("Day","CloseToClose", "Week","Month","Year","5 Years")
rownames(table.InformationTechnology2) <- listaInformationTechnology2

tex.tableInformationTechnology2 <- xtable(table.InformationTechnology2)
caption(tex.tableInformationTechnology2) <- sprintf("Variance for InformationTechnology2")
print(tex.tableInformationTechnology2,
      sep='\n' )

@


<<parameters z1 InformationTechnology2, echo=FALSE, results='hide',include=FALSE>>=


fun_gen_fun_InformationTechnology2 = function(){


FundAnalysis_z  <- c()
MarketCap    <- c()
EarningsShare <- c()
PERatio      <- c()
BookValue    <- c()
DividendYield <- c()
DividendPayDate <- c()
EarningsTimeStamp <- c()
PriceEPSEstimate <- c()
EarningsStartTime <- c()
EPSForwaerd        <- c()
EarningsEndTime  <- c()
PriceBook        <- c()
ExDividendDate   <- c()
ChangeMA50       <- c()
ChangeMA200       <- c()


i=1

for (i in i:length(listaInformationTechnology2)){
 
FundAnalysis_z[[i]] <- getQuote(listaInformationTechnology2[i], what = yahooQF(c("Market Capitalization","Earnings/Share","P/E Ratio","Book Value","Dividend Yield","Dividend Pay Date","Earnings Timestamp","Price/EPS Estimate Next Year", "Earnings Start Time","EPS Forward","Earnings End Time","Price/Book","Ex-Dividend Date","Change From 50-day Moving Average","Change From 200-day Moving Average")))

MarketCap[[i]] <- FundAnalysis_z[[i]]$`Market Capitalization`
EarningsShare[[i]] <- FundAnalysis_z[[i]]$`Earnings/Share`
PERatio[[i]]       <- FundAnalysis_z[[i]]$`P/E Ratio`
BookValue[[i]]     <- FundAnalysis_z[[i]]$`Book Value`
DividendYield[[i]] <- FundAnalysis_z[[i]]$`Dividend Yield`
DividendPayDate[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Dividend Pay Date`, origin = "1970-01-01")
EarningsTimeStamp[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Earnings Timestamp`, origin = "1970-01-01")
PriceEPSEstimate[[i]] <- FundAnalysis_z[[i]]$`Price/EPS Estimate Next Year`
EarningsStartTime[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Earnings Start Time`, origin = "1970-01-01")
EPSForwaerd[[i]] <- FundAnalysis_z[[i]]$`EPS Forward`
EarningsEndTime[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Earnings End Time`,origin = "1970-01-01")
PriceBook[[i]] <- FundAnalysis_z[[i]]$`Price/Book`
ExDividendDate[[i]] <- as.POSIXct(FundAnalysis_z[[i]]$`Ex-Dividend Date`, origin = "1970-01-01")
ChangeMA50[[i]] <- FundAnalysis_z[[i]]$`Change From 50-day MA`
ChangeMA200[[i]] <- FundAnalysis_z[[i]]$`Change From 200-day MA`}

ResFunAn <- data.frame()

ResFunAn <- rbind(MarketCap,
                  EarningsShare,
                  PERatio,
                  BookValue,
                  DividendYield,
                  DividendPayDate,
                  EarningsTimeStamp,
                  PriceEPSEstimate,
                  EarningsStartTime,
                  EPSForwaerd,
                  EarningsEndTime,
                  PriceBook,
                  ExDividendDate,
                  ChangeMA50,
                  ChangeMA200)

return(ResFunAn)

}


@


\newpage


\section{Fundamental Analysis Tables InformationTechnology}

<<Table_Final_Fundamental_analysis_InformationTechnology1 , echo=FALSE, results = "asis" >>=


Par_fund_an_InformationTechnology1 <- as.data.frame(fun_gen_fun_InformationTechnology1())

setnames(Par_fund_an_InformationTechnology1, listaInformationTechnology1)

Fund_An_Tab_Res_InformationTechnology1 <- as.data.frame(matrix("", ncol = 1, nrow = 15))



i=1

for (i in i:length(listaInformationTechnology1)) {


Fund_An_Tab_Res_InformationTechnology1 <- Par_fund_an_InformationTechnology1[listaInformationTechnology1[i]]



New_Fund_An_Tab_Res1InformationTechnology1 <- Par_fund_an_InformationTechnology1[[1,i]]

New_Fund_An_Tab_Res2InformationTechnology1 <- Par_fund_an_InformationTechnology1[[2,i]]

New_Fund_An_Tab_Res3InformationTechnology1 <-  Par_fund_an_InformationTechnology1[[3,i]]

New_Fund_An_Tab_Res4InformationTechnology1 <-  Par_fund_an_InformationTechnology1[[4,i]]

New_Fund_An_Tab_Res5InformationTechnology1 <-  Par_fund_an_InformationTechnology1[[5,i]]

New_Fund_An_Tab_Res6InformationTechnology1 <- Par_fund_an_InformationTechnology1[[6,i]]

New_Fund_An_Tab_Res7InformationTechnology1 <- Par_fund_an_InformationTechnology1[[7,i]]

New_Fund_An_Tab_Res8InformationTechnology1 <- Par_fund_an_InformationTechnology1[[8,i]]

New_Fund_An_Tab_Res9InformationTechnology1 <- Par_fund_an_InformationTechnology1[[9,i]]

New_Fund_An_Tab_Res10InformationTechnology1 <-  Par_fund_an_InformationTechnology1[[10,i]]

New_Fund_An_Tab_Res11InformationTechnology1 <- Par_fund_an_InformationTechnology1[[11,i]]

New_Fund_An_Tab_Res12InformationTechnology1 <- Par_fund_an_InformationTechnology1[[12,i]]

New_Fund_An_Tab_Res13InformationTechnology1 <- Par_fund_an_InformationTechnology1[[13,i]]

New_Fund_An_Tab_Res14InformationTechnology1 <-  Par_fund_an_InformationTechnology1[[14,i]]

New_Fund_An_Tab_Res15InformationTechnology1 <- Par_fund_an_InformationTechnology1[[15,i]]


table.FundAnalysisDMY_InformationTechnology1 <- matrix("", ncol = 2, nrow = 15)

colnames(table.FundAnalysisDMY_InformationTechnology1) <- c("Parameter", "Value")

table.FundAnalysisDMY_InformationTechnology1[1,1] <- "Market Capitalization"
table.FundAnalysisDMY_InformationTechnology1[1,2] <- sprintf("%.8g",New_Fund_An_Tab_Res1InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[2,1] <- "P/E Ratio"
table.FundAnalysisDMY_InformationTechnology1[2,2] <- sprintf("%.2f",New_Fund_An_Tab_Res3InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[3,1] <- "Earnings / Share"
table.FundAnalysisDMY_InformationTechnology1[3,2] <- sprintf("%.2f",New_Fund_An_Tab_Res2InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[4,1] <- "Price / Book"
table.FundAnalysisDMY_InformationTechnology1[4,2] <- sprintf("%.2f",New_Fund_An_Tab_Res12InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[5,1] <- "Book Value"
table.FundAnalysisDMY_InformationTechnology1[5,2] <- sprintf("%.2f",New_Fund_An_Tab_Res4InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[6,1] <- "EPS Forward"
table.FundAnalysisDMY_InformationTechnology1[6,2] <- sprintf("%.2f",New_Fund_An_Tab_Res10InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[7,1] <- "Price EPS Estimate Next Year"
table.FundAnalysisDMY_InformationTechnology1[7,2] <- sprintf("%.2f",New_Fund_An_Tab_Res8InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[8,1] <- "Dividend Yield"
table.FundAnalysisDMY_InformationTechnology1[8,2] <- sprintf("%.6f",New_Fund_An_Tab_Res5InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[9,1] <- "Dividend Pay Date"
table.FundAnalysisDMY_InformationTechnology1[9,2] <- sprintf("%s",New_Fund_An_Tab_Res6InformationTechnology1)

table.FundAnalysisDMY_InformationTechnology1[10,1] <- "Dividend Ex-Date"
table.FundAnalysisDMY_InformationTechnology1[10,2] <- sprintf("%s",New_Fund_An_Tab_Res13InformationTechnology1)


table.FundAnalysisDMY_InformationTechnology1[11,1] <- "Earnings Time Stamp"
table.FundAnalysisDMY_InformationTechnology1[11,2] <- sprintf("%s",New_Fund_An_Tab_Res7InformationTechnology1)

table.FundAnalysisDMY_InformationTechnology1[12,1] <- "Earnings Start Time"
table.FundAnalysisDMY_InformationTechnology1[12,2] <- sprintf("%s",New_Fund_An_Tab_Res9InformationTechnology1)

table.FundAnalysisDMY_InformationTechnology1[13,1] <- "Earnings End Time"
table.FundAnalysisDMY_InformationTechnology1[13,2] <- sprintf("%s",New_Fund_An_Tab_Res11InformationTechnology1)

table.FundAnalysisDMY_InformationTechnology1[14,1] <- "Change From 50-day Moving Average"
table.FundAnalysisDMY_InformationTechnology1[14,2] <- sprintf("%.2f",New_Fund_An_Tab_Res14InformationTechnology1)

table.FundAnalysisDMY_InformationTechnology1[15,1] <- "Change From 200-day Moving Average"
table.FundAnalysisDMY_InformationTechnology1[15,2] <- sprintf("%.2f",New_Fund_An_Tab_Res15InformationTechnology1)


tex.table.FundAnalysisDMY_InformationTechnology1 <- xtable(table.FundAnalysisDMY_InformationTechnology1)
caption(tex.table.FundAnalysisDMY_InformationTechnology1) <- sprintf("Fundamental Analysis parameters for %s", listaInformationTechnology1[i])
print(tex.table.FundAnalysisDMY_InformationTechnology1,
      include.rownames = FALSE,
      caption.placement = "top",
      table.placement = "ht")


}



@

<<Table_Final_Fundamental_analysis_InformationTechnology2 , echo=FALSE, results = "asis" >>=


Par_fund_an_InformationTechnology2 <- as.data.frame(fun_gen_fun_InformationTechnology2())

setnames(Par_fund_an_InformationTechnology2, listaInformationTechnology2)

Fund_An_Tab_Res_InformationTechnology2 <- as.data.frame(matrix("", ncol = 1, nrow = 15))



i=1

for (i in i:length(listaInformationTechnology2)) {


Fund_An_Tab_Res_InformationTechnology2 <- Par_fund_an_InformationTechnology2[listaInformationTechnology2[i]]



New_Fund_An_Tab_Res1InformationTechnology2 <- Par_fund_an_InformationTechnology2[[1,i]]

New_Fund_An_Tab_Res2InformationTechnology2 <- Par_fund_an_InformationTechnology2[[2,i]]

New_Fund_An_Tab_Res3InformationTechnology2 <-  Par_fund_an_InformationTechnology2[[3,i]]

New_Fund_An_Tab_Res4InformationTechnology2 <-  Par_fund_an_InformationTechnology2[[4,i]]

New_Fund_An_Tab_Res5InformationTechnology2 <-  Par_fund_an_InformationTechnology2[[5,i]]

New_Fund_An_Tab_Res6InformationTechnology2 <- Par_fund_an_InformationTechnology2[[6,i]]

New_Fund_An_Tab_Res7InformationTechnology2 <- Par_fund_an_InformationTechnology2[[7,i]]

New_Fund_An_Tab_Res8InformationTechnology2 <- Par_fund_an_InformationTechnology2[[8,i]]

New_Fund_An_Tab_Res9InformationTechnology2 <- Par_fund_an_InformationTechnology2[[9,i]]

New_Fund_An_Tab_Res10InformationTechnology2 <-  Par_fund_an_InformationTechnology2[[10,i]]

New_Fund_An_Tab_Res11InformationTechnology2 <- Par_fund_an_InformationTechnology2[[11,i]]

New_Fund_An_Tab_Res12InformationTechnology2 <- Par_fund_an_InformationTechnology2[[12,i]]

New_Fund_An_Tab_Res13InformationTechnology2 <- Par_fund_an_InformationTechnology2[[13,i]]

New_Fund_An_Tab_Res14InformationTechnology2 <-  Par_fund_an_InformationTechnology2[[14,i]]

New_Fund_An_Tab_Res15InformationTechnology2 <- Par_fund_an_InformationTechnology2[[15,i]]


table.FundAnalysisDMY_InformationTechnology2 <- matrix("", ncol = 2, nrow = 15)

colnames(table.FundAnalysisDMY_InformationTechnology2) <- c("Parameter", "Value")

table.FundAnalysisDMY_InformationTechnology2[1,1] <- "Market Capitalization"
table.FundAnalysisDMY_InformationTechnology2[1,2] <- sprintf("%.8g",New_Fund_An_Tab_Res1InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[2,1] <- "P/E Ratio"
table.FundAnalysisDMY_InformationTechnology2[2,2] <- sprintf("%.2f",New_Fund_An_Tab_Res3InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[3,1] <- "Earnings / Share"
table.FundAnalysisDMY_InformationTechnology2[3,2] <- sprintf("%.2f",New_Fund_An_Tab_Res2InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[4,1] <- "Price / Book"
table.FundAnalysisDMY_InformationTechnology2[4,2] <- sprintf("%.2f",New_Fund_An_Tab_Res12InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[5,1] <- "Book Value"
table.FundAnalysisDMY_InformationTechnology2[5,2] <- sprintf("%.2f",New_Fund_An_Tab_Res4InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[6,1] <- "EPS Forward"
table.FundAnalysisDMY_InformationTechnology2[6,2] <- sprintf("%.2f",New_Fund_An_Tab_Res10InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[7,1] <- "Price EPS Estimate Next Year"
table.FundAnalysisDMY_InformationTechnology2[7,2] <- sprintf("%.2f",New_Fund_An_Tab_Res8InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[8,1] <- "Dividend Yield"
table.FundAnalysisDMY_InformationTechnology2[8,2] <- sprintf("%.6f",New_Fund_An_Tab_Res5InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[9,1] <- "Dividend Pay Date"
table.FundAnalysisDMY_InformationTechnology2[9,2] <- sprintf("%s",New_Fund_An_Tab_Res6InformationTechnology2)

table.FundAnalysisDMY_InformationTechnology2[10,1] <- "Dividend Ex-Date"
table.FundAnalysisDMY_InformationTechnology2[10,2] <- sprintf("%s",New_Fund_An_Tab_Res13InformationTechnology2)


table.FundAnalysisDMY_InformationTechnology2[11,1] <- "Earnings Time Stamp"
table.FundAnalysisDMY_InformationTechnology2[11,2] <- sprintf("%s",New_Fund_An_Tab_Res7InformationTechnology2)

table.FundAnalysisDMY_InformationTechnology2[12,1] <- "Earnings Start Time"
table.FundAnalysisDMY_InformationTechnology2[12,2] <- sprintf("%s",New_Fund_An_Tab_Res9InformationTechnology2)

table.FundAnalysisDMY_InformationTechnology2[13,1] <- "Earnings End Time"
table.FundAnalysisDMY_InformationTechnology2[13,2] <- sprintf("%s",New_Fund_An_Tab_Res11InformationTechnology2)

table.FundAnalysisDMY_InformationTechnology2[14,1] <- "Change From 50-day Moving Average"
table.FundAnalysisDMY_InformationTechnology2[14,2] <- sprintf("%.2f",New_Fund_An_Tab_Res14InformationTechnology2)

table.FundAnalysisDMY_InformationTechnology2[15,1] <- "Change From 200-day Moving Average"
table.FundAnalysisDMY_InformationTechnology2[15,2] <- sprintf("%.2f",New_Fund_An_Tab_Res15InformationTechnology2)


tex.table.FundAnalysisDMY_InformationTechnology2 <- xtable(table.FundAnalysisDMY_InformationTechnology2)
caption(tex.table.FundAnalysisDMY_InformationTechnology2) <- sprintf("Fundamental Analysis parameters for %s", listaInformationTechnology2[i])
print(tex.table.FundAnalysisDMY_InformationTechnology2,
      include.rownames = FALSE,
      caption.placement = "top",
      table.placement = "ht")


}



@

\FloatBarrier

\clearpage


\thispagestyle{empty}

\end{document}